version: '3.6'
services:
  website:
    image: website
    container_name: website_container
    ports:
      - "82:80"
      - "445:443"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"

    volumes:
      - .:/root/www/
      - /root/shared_pdf:/var/www/html/shared_pdf
    tty: true
    networks:
      - greed_net



networks:
  greed_net:
    name: greed_net
    external: true

