services:
  greed-website:
    image: website
    container_name: website-container
    # ports:
    #   - "82:80"
    restart: always
    networks:
      - greed_net

networks:
  greed_net:
    name: greed_net
    external: true
