version: '3.6'
services:
  discord:
    image: website
    container_name: website_container
    ports:
      - "82:80"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    expose:
      - "82"
    volumes:
      - .:/root/www/
    tty: true
