services:
  greed-website:
    build:
      context: .
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://localhost:82}
    image: website
    container_name: website-container
    ports:
      - "82:80"
    restart: always
    networks:
      - greed_net


networks:
  greed_net:
    name: greed_net
    external: true
