# Generated by Django 4.1.2 on 2022-11-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapi', '0002_stockdata_announcment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='status',
            field=models.IntegerField(),
        ),
    ]
