# Generated by Django 4.1.2 on 2022-11-13 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapi', '0003_alter_stockdata_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stockdata',
            table='stockdata',
        ),
    ]
