# Generated by Django 4.1.2 on 2022-11-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapi', '0004_alter_stockdata_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='stock_price',
            field=models.FloatField(),
        ),
    ]
